package com.lifo.util.model

/**
 * Complete Avatar entity as stored in Firestore.
 * Path: users/{userId}/avatars/{avatarId}
 */
data class Avatar(
    val id: String = "",
    val name: String = "",
    val status: AvatarStatus = AvatarStatus.PENDING,
    val createdAt: Long = 0L,
    val vrmUrl: String = "",
    val thumbnailUrl: String = "",

    // Voice
    val voiceId: String = "",
    val voiceConfig: VoiceConfig = VoiceConfig(),

    // System Prompt (generated by AI)
    val systemPrompt: AvatarSystemPrompt = AvatarSystemPrompt(),

    // Structured character data
    val characterProfile: CharacterProfile = CharacterProfile(),

    // VRM 3D appearance params
    val vrmParams: VrmParams = VrmParams(),
)

enum class AvatarStatus {
    PENDING,
    GENERATING,
    PROMPT_READY,
    READY,
    ERROR
}

data class VoiceConfig(
    val speakingRate: Float = 1.0f,
    val volumeGainDb: Float = 0.0f,
    val languageCode: String = "it-IT",
)

data class AvatarSystemPrompt(
    val raw: String = "",
    val version: Int = 1,
    val generatedAt: Long = 0L,
)

data class CharacterProfile(
    val coreIdentity: String = "",
    val traits: List<String> = emptyList(),
    val values: List<String> = emptyList(),
    val biases: List<String> = emptyList(),
    val coreWound: String = "",
    val coreStrength: String = "",
    val primaryNeed: String = "",
    val goals: String = "",
    val avoidTopics: List<String> = emptyList(),
    val culturalReference: String = "",
    val communicationStyle: CommunicationStyle = CommunicationStyle(),
    val emotionalProfile: EmotionalProfile = EmotionalProfile(),
)

data class CommunicationStyle(
    val directness: Float = 0.5f,
    val humor: Float = 0.5f,
    val speakingRhythm: String = "",
)

data class EmotionalProfile(
    val attachmentStyle: String = "",
    val stressResponse: String = "",
    val affectionStyle: String = "",
    val vulnerabilityTriggers: List<String> = emptyList(),
)

data class VrmParams(
    val bodyType: String = "",
    val height: Float = 170f,
    val skinTone: String = "",
    val hairStyle: String = "",
    val hairColor: String = "",
    val outfitType: String = "",
    val extras: List<String> = emptyList(),
)

// ═══════════════════════════════════════════
// Avatar Creation Form — Wizard data model
// ═══════════════════════════════════════════

/**
 * Complete form data collected from the 6-section wizard.
 * This is the input that gets sent to the Cloud Function
 * to generate the system prompt + trigger VRM creation.
 */
data class AvatarCreationForm(
    // Section 1 — Identity
    val name: String = "",
    val perceivedAge: Int = 25,
    val gender: GenderIdentity = GenderIdentity.NOT_SPECIFIED,
    val languages: List<String> = listOf("Italiano"),

    // Section 2 — Appearance → VRM
    val appearance: VrmParams = VrmParams(),

    // Section 3 — Personality
    val traits: List<String> = emptyList(),
    val stressResponse: StressResponse = StressResponse.RATIONALIZE,
    val directness: Float = 0.5f,
    val humor: Float = 0.5f,
    val decisionStyle: DecisionStyle = DecisionStyle.INSTINCT,
    val authorityRelation: Float = 0.5f,

    // Section 4 — Values & Bias
    val values: String = "",
    val biases: List<String> = emptyList(),
    val coreWound: String = "",
    val coreStrength: String = "",
    val culturalBackground: String = "",
    val culturalReference: String = "",

    // Section 5 — Needs & Desires
    val primaryNeed: PrimaryNeed = PrimaryNeed.BE_HEARD,
    val goals: String = "",
    val avoidTopics: String = "",
    val engagementFrequency: EngagementFrequency = EngagementFrequency.DAILY,

    // Section 6 — Voice & Style
    val voiceId: String = "Aoede",
    val speakingRate: Float = 1.0f,
    val voiceTone: VoiceTone = VoiceTone.WARM,
    val pauseStyle: Boolean = false,
    val volumeGain: Float = 0.0f,

    // Section 7 — Emotional Style
    val attachmentStyle: AttachmentStyle = AttachmentStyle.SECURE,
    val jealousyLevel: Float = 0.3f,
    val affectionStyle: String = "",
    val vulnerabilityTriggers: String = "",
    val emotionalBarrier: String = "",
)

// ═══════════════════════════════════════════
// Enums for form selections
// ═══════════════════════════════════════════

enum class GenderIdentity(val displayName: String) {
    MALE("Maschile"),
    FEMALE("Femminile"),
    NON_BINARY("Non-binario"),
    NOT_SPECIFIED("Non specificato"),
}

enum class StressResponse(val displayName: String) {
    SHUT_DOWN("Si chiude in se stesso"),
    EXPLODE("Esplode"),
    RATIONALIZE("Razionalizza"),
    SEEK_HELP("Cerca aiuto"),
}

enum class DecisionStyle(val displayName: String) {
    INSTINCT("Istinto"),
    DATA("Dati e analisi"),
    EMOTIONS("Emozioni"),
    CONSENSUS("Consenso del gruppo"),
}

enum class PrimaryNeed(val displayName: String) {
    BE_HEARD("Essere ascoltato"),
    LEARN("Imparare e crescere"),
    BE_CHALLENGED("Essere sfidato"),
    FEEL_SAFE("Sentirsi al sicuro"),
}

enum class EngagementFrequency(val displayName: String) {
    MULTIPLE_DAILY("Piu' volte al giorno"),
    DAILY("Una volta al giorno"),
    FEW_WEEKLY("Qualche volta a settimana"),
    WEEKLY("Una volta a settimana"),
}

enum class VoiceTone(val displayName: String) {
    WARM("Caldo"),
    NEUTRAL("Neutro"),
    FORMAL("Formale"),
    PLAYFUL("Giocoso"),
}

enum class AttachmentStyle(val displayName: String) {
    SECURE("Sicuro"),
    ANXIOUS("Ansioso"),
    AVOIDANT("Evitante"),
    DISORGANIZED("Disorganizzato"),
}

// Voice presets compatible with Gemini Live API
enum class GeminiVoice(val voiceId: String, val displayName: String, val description: String) {
    AOEDE("Aoede", "Aoede", "Caldo, femminile, melodico"),
    CHARON("Charon", "Charon", "Profondo, maschile, grave"),
    FENRIR("Fenrir", "Fenrir", "Energico, maschile, diretto"),
    LAOMEDEIA("Laomedeia", "Laomedeia", "Neutro, chiaro, preciso"),
    KORE("Kore", "Kore", "Giovane, femminile, vivace"),
    ORUS("Orus", "Orus", "Caldo, maschile, pacato"),
}

// Predefined personality traits for tag picker
object PersonalityTraits {
    val all = listOf(
        "Empatico", "Sarcastico", "Ribelle", "Riflessivo", "Impulsivo",
        "Protettivo", "Curioso", "Perfezionista", "Creativo", "Pragmatico",
        "Introverso", "Estroverso", "Ironico", "Serio", "Avventuroso",
        "Calmo", "Intenso", "Leale", "Indipendente", "Sensibile",
        "Determinato", "Flessibile", "Carismatico", "Riservato", "Ottimista",
        "Cinico", "Affettuoso", "Distaccato", "Ambizioso", "Sognatore",
    )
}

// Predefined biases for multi-select
object RecognizedBiases {
    val all = listOf(
        "Perfezionismo", "Sfiducia negli altri", "Pessimismo",
        "Impazienza", "Giudizio rapido", "Evitamento del conflitto",
        "Bisogno di controllo", "Idealizzazione", "Cinismo",
        "Tendenza a compiacere", "Autosabotaggio", "Overthinking",
    )
}

// Body types for VRM
object BodyTypes {
    val all = listOf(
        "Esile", "Snello", "Atletico", "Medio", "Robusto", "Curvy",
    )
}

// Hair styles for visual picker
object HairStyles {
    val all = listOf(
        "Corto classico", "Corto spettinato", "Medio mosso", "Lungo liscio",
        "Lungo riccio", "Rasato", "Mohawk", "Bob", "Trecce", "Coda di cavallo",
        "Afro", "Undercut",
    )
}

// Outfit styles for visual picker
object OutfitStyles {
    val all = listOf(
        "Casual streetwear", "Elegante formale", "Sportivo",
        "Fantasy", "Sci-fi / Futuristico", "Gothic",
        "Bohemian", "Minimale", "Cyberpunk",
        "Vintage", "Preppy", "Grunge",
    )
}

// Named hair colors for visual picker (used by AppearanceSection + VRM matching)
object HairColors {
    val all = listOf(
        "Nero", "Castano", "Biondo", "Rosso", "Bianco",
        "Grigio", "Argento", "Blu", "Rosa", "Arancione",
        "Viola", "Platino",
    )
}

// Named skin tones for visual picker (used by AppearanceSection + VRM matching)
object SkinTones {
    val all = listOf(
        "Chiaro", "Medio", "Olivastro", "Scuro", "Ambrato",
    )
}

// Special extras for avatar customization
object AvatarExtras {
    val all = listOf(
        "Orecchie elfiche", "Orecchie da gatto", "Orecchie di volpe",
        "Coda", "Ali piumate", "Ali nere",
        "Corna", "Aureola",
        "Occhiali", "Cappuccio", "Maschera",
        "Cicatrici", "Tatuaggi", "Piercing", "Lentiggini",
        "Neo", "Eterocromia",
    )
}
