package com.lifo.util.mapper

import com.lifo.shared.model.ProfileSettingsProto
import com.lifo.util.model.ProfileSettings

fun ProfileSettings.toProto(): ProfileSettingsProto = ProfileSettingsProto(
    id = id,
    ownerId = ownerId,
    createdAtMillis = createdAtMillis,
    updatedAtMillis = updatedAtMillis,
    isOnboardingCompleted = isOnboardingCompleted,
    displayName = displayName,
    fullName = fullName,
    dateOfBirth = dateOfBirth,
    gender = gender,
    height = height,
    weight = weight,
    location = location,
    primaryConcerns = primaryConcerns,
    mentalHealthHistory = mentalHealthHistory,
    currentTherapy = currentTherapy,
    medication = medication,
    occupation = occupation,
    sleepHoursAvg = sleepHoursAvg,
    exerciseFrequency = exerciseFrequency,
    socialSupport = socialSupport,
    primaryGoals = primaryGoals,
    preferredCopingStrategies = preferredCopingStrategies,
    aiTone = aiTone,
    reminderFrequency = reminderFrequency,
    topicsToAvoid = topicsToAvoid,
    shareDataForResearch = shareDataForResearch,
    enableAdvancedInsights = enableAdvancedInsights,
)

fun ProfileSettingsProto.toDomain(): ProfileSettings = ProfileSettings(
    id = id,
    ownerId = ownerId,
    createdAtMillis = createdAtMillis,
    updatedAtMillis = updatedAtMillis,
    isOnboardingCompleted = isOnboardingCompleted,
    displayName = displayName,
    fullName = fullName,
    dateOfBirth = dateOfBirth,
    gender = gender,
    height = height,
    weight = weight,
    location = location,
    primaryConcerns = primaryConcerns,
    mentalHealthHistory = mentalHealthHistory,
    currentTherapy = currentTherapy,
    medication = medication,
    occupation = occupation,
    sleepHoursAvg = sleepHoursAvg,
    exerciseFrequency = exerciseFrequency,
    socialSupport = socialSupport,
    primaryGoals = primaryGoals,
    preferredCopingStrategies = preferredCopingStrategies,
    aiTone = aiTone,
    reminderFrequency = reminderFrequency,
    topicsToAvoid = topicsToAvoid,
    shareDataForResearch = shareDataForResearch,
    enableAdvancedInsights = enableAdvancedInsights,
)
