package com.lifo.chat.domain.audio

import android.content.Context
import android.media.AudioDeviceInfo
import android.media.AudioManager
import android.media.AudioRecord
import android.media.audiofx.AcousticEchoCanceler
import android.media.audiofx.AutomaticGainControl
import android.media.audiofx.NoiseSuppressor
import android.os.Build
import android.util.Log
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Full-Duplex Audio Session Manager
 *
 * Manages the critical synchronization between AudioRecord (input) and
 * AudioTrack (output) for transparent hardware AEC (Acoustic Echo Cancellation).
 *
 * ## Android HAL AEC Mechanism
 *
 * ```
 * AudioTrack(USAGE_MEDIA, sessionId=N)
 *   → HAL plays AI voice through speaker (full-bandwidth media quality)
 *   → HAL captures ECHO_REFERENCE at hardware level from speaker output
 *   ↓
 * AEC in HAL (< 10ms latency)
 *   → Subtracts echo reference from mic input in real-time
 *   → Outputs clean user voice (echo removed)
 *   ↓
 * AudioRecord(VOICE_COMMUNICATION, sessionId=N)
 *   → App receives AEC-processed audio (clean user speech)
 *   → Sent to Gemini Live API or processed by local VAD
 * ```
 *
 * ## Key Requirements for AEC
 *
 * 1. AudioRecord uses AudioSource.VOICE_COMMUNICATION
 *    → Activates HAL preprocessing pipeline (AEC, AGC, NS)
 *
 * 2. AudioTrack uses USAGE_MEDIA
 *    → Full-bandwidth output (no telephonic codec/DSP)
 *    → AEC reference comes from HAL ECHO_REFERENCE (hardware level, usage-independent)
 *    → USAGE_VOICE_COMMUNICATION gave telephonic quality; USAGE_ASSISTANT routed to earpiece
 *
 * 3. Same audioSessionId on both Record and Track
 *    → Links explicit AcousticEchoCanceler AudioEffect to reference signal
 *
 * 4. AudioEffect instances MUST be stored as class fields
 *    → If garbage collected, effects stop working silently!
 *
 * 5. AudioManager.MODE_IN_COMMUNICATION + speaker routing
 *    → MODE_IN_COMMUNICATION activates HAL AEC (MODE_NORMAL doesn't on most devices!)
 *    → setSpeakerphoneOn(true) / setCommunicationDevice(SPEAKER) keeps speaker output
 *    → Same pattern used by WhatsApp/Telegram/Discord speakerphone mode
 */
@Singleton
class FullDuplexAudioSession @Inject constructor(
    @ApplicationContext private val context: Context
) {
    companion object {
        private const val TAG = "FullDuplexSession"
    }

    // Shared audio session ID for AEC synchronization
    private var sharedSessionId: Int = AudioManager.AUDIO_SESSION_ID_GENERATE

    // Audio effects — MUST be stored as class fields to prevent garbage collection!
    // If these were local variables, the GC would destroy them and the HAL
    // effects would stop working silently. This was the #1 full-duplex bug.
    private var acousticEchoCanceler: AcousticEchoCanceler? = null
    private var noiseSuppressor: NoiseSuppressor? = null
    private var automaticGainControl: AutomaticGainControl? = null

    // Session state
    private val _isSessionActive = MutableStateFlow(false)
    val isSessionActive: StateFlow<Boolean> = _isSessionActive.asStateFlow()

    private val _aecEnabled = MutableStateFlow(false)
    val aecEnabled: StateFlow<Boolean> = _aecEnabled.asStateFlow()

    private val _nsEnabled = MutableStateFlow(false)
    val nsEnabled: StateFlow<Boolean> = _nsEnabled.asStateFlow()

    private val _agcEnabled = MutableStateFlow(false)
    val agcEnabled: StateFlow<Boolean> = _agcEnabled.asStateFlow()

    private val audioManager = context.getSystemService(Context.AUDIO_SERVICE) as AudioManager

    /**
     * Called after AudioRecord is created to capture its session ID
     * and attach audio effects that persist for the session lifetime.
     *
     * MUST be called before creating AudioTrack so the session ID is available.
     *
     * @param audioRecord The initialized AudioRecord instance
     */
    fun onInputCreated(audioRecord: AudioRecord) {
        // Capture the session ID generated by AudioRecord
        sharedSessionId = audioRecord.audioSessionId
        Log.d(TAG, "🔗 Captured input session ID: $sharedSessionId")

        // Attach persistent audio effects to this session
        attachAudioEffects(sharedSessionId)

        _isSessionActive.value = true

        Log.d(TAG, "✅ Full-duplex session active:")
        Log.d(TAG, "   Session ID: $sharedSessionId")
        Log.d(TAG, "   AEC: ${_aecEnabled.value} (available: ${AcousticEchoCanceler.isAvailable()})")
        Log.d(TAG, "   NS:  ${_nsEnabled.value} (available: ${NoiseSuppressor.isAvailable()})")
        Log.d(TAG, "   AGC: ${_agcEnabled.value} (available: ${AutomaticGainControl.isAvailable()})")
    }

    /**
     * Get the shared session ID for AudioTrack creation.
     * AudioTrack MUST use this session ID so AEC has a reference signal.
     *
     * @return The shared session ID, or AUDIO_SESSION_ID_GENERATE if no session
     */
    fun getOutputSessionId(): Int = sharedSessionId

    /**
     * Check if a valid session is active.
     */
    fun hasActiveSession(): Boolean =
        sharedSessionId != AudioManager.AUDIO_SESSION_ID_GENERATE && _isSessionActive.value

    /**
     * Attach hardware audio effects to the audio session.
     *
     * These are stored as class fields — critical for lifecycle management.
     * Local variables would be garbage collected, silently disabling the effects.
     */
    private fun attachAudioEffects(sessionId: Int) {
        // Release any existing effects first
        releaseEffects()

        // AEC — the critical effect for full-duplex
        if (AcousticEchoCanceler.isAvailable()) {
            try {
                acousticEchoCanceler = AcousticEchoCanceler.create(sessionId)?.also { aec ->
                    aec.enabled = true
                    _aecEnabled.value = true
                    Log.d(TAG, "✅ AEC enabled on session $sessionId")
                }
            } catch (e: Exception) {
                Log.w(TAG, "⚠️ Failed to create AEC", e)
            }
        } else {
            Log.w(TAG, "⚠️ AEC not available on this device")
        }

        // NS — Noise Suppression
        if (NoiseSuppressor.isAvailable()) {
            try {
                noiseSuppressor = NoiseSuppressor.create(sessionId)?.also { ns ->
                    ns.enabled = true
                    _nsEnabled.value = true
                    Log.d(TAG, "✅ NS enabled on session $sessionId")
                }
            } catch (e: Exception) {
                Log.w(TAG, "⚠️ Failed to create NS", e)
            }
        } else {
            Log.w(TAG, "⚠️ NS not available on this device")
        }

        // AGC — Automatic Gain Control
        if (AutomaticGainControl.isAvailable()) {
            try {
                automaticGainControl = AutomaticGainControl.create(sessionId)?.also { agc ->
                    agc.enabled = true
                    _agcEnabled.value = true
                    Log.d(TAG, "✅ AGC enabled on session $sessionId")
                }
            } catch (e: Exception) {
                Log.w(TAG, "⚠️ Failed to create AGC", e)
            }
        } else {
            Log.w(TAG, "⚠️ AGC not available on this device")
        }
    }

    /**
     * Release audio effects. Called when the session ends.
     */
    private fun releaseEffects() {
        acousticEchoCanceler?.let {
            try {
                it.enabled = false
                it.release()
            } catch (_: Exception) { }
        }
        acousticEchoCanceler = null
        _aecEnabled.value = false

        noiseSuppressor?.let {
            try {
                it.enabled = false
                it.release()
            } catch (_: Exception) { }
        }
        noiseSuppressor = null
        _nsEnabled.value = false

        automaticGainControl?.let {
            try {
                it.enabled = false
                it.release()
            } catch (_: Exception) { }
        }
        automaticGainControl = null
        _agcEnabled.value = false
    }

    /**
     * Configure audio mode for full-duplex assistant.
     *
     * KEY INSIGHT: MODE_NORMAL does NOT reliably activate hardware AEC on most devices.
     * The HAL only enables AEC when MODE_IN_COMMUNICATION is set (same code path as phone calls).
     *
     * Solution (same as WhatsApp/Telegram/Discord speakerphone):
     * 1. MODE_IN_COMMUNICATION → activates HAL AEC pipeline
     * 2. Force speaker routing → audio comes out of speaker (not earpiece)
     *
     * Result: AEC works + speaker output = full-duplex without echo
     */
    fun configureAudioMode() {
        // Step 1: Enable communication mode (activates HAL AEC)
        audioManager.mode = AudioManager.MODE_IN_COMMUNICATION
        Log.d(TAG, "🔊 Audio mode: MODE_IN_COMMUNICATION (HAL AEC active)")

        // Step 2: Force speaker routing (prevents earpiece fallback)
        forceSpeakerRouting()
    }

    /**
     * Force audio output to the built-in speaker while in MODE_IN_COMMUNICATION.
     *
     * API 31+ uses setCommunicationDevice() (modern API).
     * API <31 uses setSpeakerphoneOn() (deprecated but still functional).
     */
    @Suppress("DEPRECATION")
    private fun forceSpeakerRouting() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            // API 31+: Use setCommunicationDevice for explicit speaker routing
            try {
                val speaker = audioManager.availableCommunicationDevices.firstOrNull {
                    it.type == AudioDeviceInfo.TYPE_BUILTIN_SPEAKER
                }
                if (speaker != null) {
                    val success = audioManager.setCommunicationDevice(speaker)
                    Log.d(TAG, "🔊 Speaker routing (API 31+): setCommunicationDevice=${success}")
                } else {
                    // Fallback: try deprecated method
                    audioManager.isSpeakerphoneOn = true
                    Log.d(TAG, "🔊 Speaker routing: fallback to setSpeakerphoneOn (no speaker device found)")
                }
            } catch (e: Exception) {
                Log.w(TAG, "⚠️ setCommunicationDevice failed, using fallback", e)
                audioManager.isSpeakerphoneOn = true
            }
        } else {
            // API <31: setSpeakerphoneOn (deprecated but reliable)
            audioManager.isSpeakerphoneOn = true
            Log.d(TAG, "🔊 Speaker routing (API <31): setSpeakerphoneOn=true")
        }
    }

    /**
     * Reset audio mode and speaker routing to defaults.
     */
    @Suppress("DEPRECATION")
    fun resetAudioMode() {
        // Reset speaker routing
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            try {
                audioManager.clearCommunicationDevice()
            } catch (e: Exception) {
                Log.w(TAG, "⚠️ clearCommunicationDevice failed", e)
            }
        }
        audioManager.isSpeakerphoneOn = false

        // Reset audio mode
        audioManager.mode = AudioManager.MODE_NORMAL
        Log.d(TAG, "🔊 Audio mode reset to MODE_NORMAL, speaker routing cleared")
    }

    /**
     * Get diagnostic information about the full-duplex session.
     */
    @Suppress("DEPRECATION")
    fun getDiagnostics(): Map<String, Any> = mapOf(
        "sessionId" to sharedSessionId,
        "isActive" to _isSessionActive.value,
        "aecEnabled" to _aecEnabled.value,
        "aecAvailable" to AcousticEchoCanceler.isAvailable(),
        "nsEnabled" to _nsEnabled.value,
        "nsAvailable" to NoiseSuppressor.isAvailable(),
        "agcEnabled" to _agcEnabled.value,
        "agcAvailable" to AutomaticGainControl.isAvailable(),
        "audioMode" to audioManager.mode,
        "isSpeakerphoneOn" to audioManager.isSpeakerphoneOn,
        "modeInCommunication" to (audioManager.mode == AudioManager.MODE_IN_COMMUNICATION)
    )

    /**
     * Release all resources. Call when the audio session is complete.
     */
    fun release() {
        Log.d(TAG, "🧹 Releasing full-duplex session (sessionId=$sharedSessionId)")
        releaseEffects()
        sharedSessionId = AudioManager.AUDIO_SESSION_ID_GENERATE
        _isSessionActive.value = false
        resetAudioMode()
    }
}
