package com.lifo.chat.domain.audio

import android.content.Context
import android.media.AudioDeviceInfo
import android.media.AudioManager
import android.media.AudioRecord
import android.media.audiofx.AcousticEchoCanceler
import android.media.audiofx.AutomaticGainControl
import android.media.audiofx.NoiseSuppressor
import android.os.Build

import kotlinx.coroutines.flow.MutableStateFlow
import kotlinx.coroutines.flow.StateFlow
import kotlinx.coroutines.flow.asStateFlow

/**
 * Full-Duplex Audio Session Manager
 *
 * Manages the critical synchronization between AudioRecord (input) and
 * AudioTrack (output) for transparent hardware AEC (Acoustic Echo Cancellation).
 *
 * ## Android HAL AEC Mechanism
 *
 * ```
 * AudioTrack(USAGE_MEDIA, sessionId=N)
 *   → HAL plays AI voice through speaker (full-bandwidth media quality)
 *   → HAL captures ECHO_REFERENCE at hardware level from speaker output
 *   ↓
 * AEC in HAL (< 10ms latency)
 *   → Subtracts echo reference from mic input in real-time
 *   → Outputs clean user voice (echo removed)
 *   ↓
 * AudioRecord(VOICE_COMMUNICATION, sessionId=N)
 *   → App receives AEC-processed audio (clean user speech)
 *   → Sent to Gemini Live API or processed by local VAD
 * ```
 *
 * ## Key Requirements for AEC
 *
 * 1. AudioRecord uses AudioSource.VOICE_COMMUNICATION
 *    → Activates HAL preprocessing pipeline (AEC, AGC, NS)
 *
 * 2. AudioTrack uses USAGE_MEDIA
 *    → Full-bandwidth output (no telephonic codec/DSP)
 *    → AEC reference comes from HAL ECHO_REFERENCE (hardware level, usage-independent)
 *    → USAGE_VOICE_COMMUNICATION gave telephonic quality; USAGE_ASSISTANT routed to earpiece
 *
 * 3. Same audioSessionId on both Record and Track
 *    → Links explicit AcousticEchoCanceler AudioEffect to reference signal
 *
 * 4. AudioEffect instances MUST be stored as class fields
 *    → If garbage collected, effects stop working silently!
 *
 * 5. AudioManager.MODE_IN_COMMUNICATION + speaker routing
 *    → MODE_IN_COMMUNICATION activates HAL AEC (MODE_NORMAL doesn't on most devices!)
 *    → setSpeakerphoneOn(true) / setCommunicationDevice(SPEAKER) keeps speaker output
 *    → Same pattern used by WhatsApp/Telegram/Discord speakerphone mode
 */
class FullDuplexAudioSession constructor(
    private val context: Context
) {
    // Shared audio session ID for AEC synchronization
    private var sharedSessionId: Int = AudioManager.AUDIO_SESSION_ID_GENERATE

    // Headphone mode — when true, AEC is unnecessary (no acoustic echo path)
    private val _isHeadphoneMode = MutableStateFlow(false)
    val isHeadphoneMode: StateFlow<Boolean> = _isHeadphoneMode.asStateFlow()

    // Audio effects — MUST be stored as class fields to prevent garbage collection!
    // If these were local variables, the GC would destroy them and the HAL
    // effects would stop working silently. This was the #1 full-duplex bug.
    private var acousticEchoCanceler: AcousticEchoCanceler? = null
    private var noiseSuppressor: NoiseSuppressor? = null
    private var automaticGainControl: AutomaticGainControl? = null

    // Session state
    private val _isSessionActive = MutableStateFlow(false)
    val isSessionActive: StateFlow<Boolean> = _isSessionActive.asStateFlow()

    private val _aecEnabled = MutableStateFlow(false)
    val aecEnabled: StateFlow<Boolean> = _aecEnabled.asStateFlow()

    private val _nsEnabled = MutableStateFlow(false)
    val nsEnabled: StateFlow<Boolean> = _nsEnabled.asStateFlow()

    private val _agcEnabled = MutableStateFlow(false)
    val agcEnabled: StateFlow<Boolean> = _agcEnabled.asStateFlow()

    private val audioManager = context.getSystemService(Context.AUDIO_SERVICE) as AudioManager

    /**
     * Called after AudioRecord is created to capture its session ID
     * and attach audio effects that persist for the session lifetime.
     *
     * MUST be called before creating AudioTrack so the session ID is available.
     *
     * @param audioRecord The initialized AudioRecord instance
     */
    fun onInputCreated(audioRecord: AudioRecord) {
        // Capture the session ID generated by AudioRecord
        sharedSessionId = audioRecord.audioSessionId
        println("[FullDuplexSession] Captured input session ID: $sharedSessionId")

        // Attach persistent audio effects to this session
        attachAudioEffects(sharedSessionId)

        _isSessionActive.value = true

        println("[FullDuplexSession] Full-duplex session active:")
        println("[FullDuplexSession]    Session ID: $sharedSessionId")
        println("[FullDuplexSession]    AEC: ${_aecEnabled.value} (available: ${AcousticEchoCanceler.isAvailable()})")
        println("[FullDuplexSession]    NS:  ${_nsEnabled.value} (available: ${NoiseSuppressor.isAvailable()})")
        println("[FullDuplexSession]    AGC: ${_agcEnabled.value} (available: ${AutomaticGainControl.isAvailable()})")
    }

    /**
     * Get the shared session ID for AudioTrack creation.
     * AudioTrack MUST use this session ID so AEC has a reference signal.
     *
     * @return The shared session ID, or AUDIO_SESSION_ID_GENERATE if no session
     */
    fun getOutputSessionId(): Int = sharedSessionId

    /**
     * Pre-generate a session ID for Oboe native streams.
     *
     * Oboe requires the sessionId at stream open time, BEFORE AudioRecord is created.
     * This inverts the current flow (AudioRecord → capture sessionId → use for AudioTrack).
     * With Oboe: generateSessionId() → pass to both Oboe playback AND recording streams.
     */
    fun getOrCreateSessionId(): Int {
        if (sharedSessionId == AudioManager.AUDIO_SESSION_ID_GENERATE) {
            sharedSessionId = audioManager.generateAudioSessionId()
            println("[FullDuplexSession] Pre-generated session ID: $sharedSessionId")
        }
        return sharedSessionId
    }

    /**
     * Check if a valid session is active.
     */
    fun hasActiveSession(): Boolean =
        sharedSessionId != AudioManager.AUDIO_SESSION_ID_GENERATE && _isSessionActive.value

    /**
     * Attach hardware audio effects to the audio session.
     *
     * These are stored as class fields — critical for lifecycle management.
     * Local variables would be garbage collected, silently disabling the effects.
     */
    private fun attachAudioEffects(sessionId: Int) {
        // Release any existing effects first
        releaseEffects()

        // AEC — the critical effect for full-duplex
        if (AcousticEchoCanceler.isAvailable()) {
            try {
                acousticEchoCanceler = AcousticEchoCanceler.create(sessionId)?.also { aec ->
                    aec.enabled = true
                    _aecEnabled.value = true
                    println("[FullDuplexSession] AEC enabled on session $sessionId")
                }
            } catch (e: Exception) {
                println("[FullDuplexSession] WARNING: Failed to create AEC: ${e.message}")
            }
        } else {
            println("[FullDuplexSession] WARNING: AEC not available on this device")
        }

        // NS — Noise Suppression
        if (NoiseSuppressor.isAvailable()) {
            try {
                noiseSuppressor = NoiseSuppressor.create(sessionId)?.also { ns ->
                    ns.enabled = true
                    _nsEnabled.value = true
                    println("[FullDuplexSession] NS enabled on session $sessionId")
                }
            } catch (e: Exception) {
                println("[FullDuplexSession] WARNING: Failed to create NS: ${e.message}")
            }
        } else {
            println("[FullDuplexSession] WARNING: NS not available on this device")
        }

        // AGC — Automatic Gain Control
        if (AutomaticGainControl.isAvailable()) {
            try {
                automaticGainControl = AutomaticGainControl.create(sessionId)?.also { agc ->
                    agc.enabled = true
                    _agcEnabled.value = true
                    println("[FullDuplexSession] AGC enabled on session $sessionId")
                }
            } catch (e: Exception) {
                println("[FullDuplexSession] WARNING: Failed to create AGC: ${e.message}")
            }
        } else {
            println("[FullDuplexSession] WARNING: AGC not available on this device")
        }
    }

    /**
     * Release audio effects. Called when the session ends.
     */
    private fun releaseEffects() {
        acousticEchoCanceler?.let {
            try {
                it.enabled = false
                it.release()
            } catch (_: Exception) { }
        }
        acousticEchoCanceler = null
        _aecEnabled.value = false

        noiseSuppressor?.let {
            try {
                it.enabled = false
                it.release()
            } catch (_: Exception) { }
        }
        noiseSuppressor = null
        _nsEnabled.value = false

        automaticGainControl?.let {
            try {
                it.enabled = false
                it.release()
            } catch (_: Exception) { }
        }
        automaticGainControl = null
        _agcEnabled.value = false
    }

    /**
     * Configure audio mode for full-duplex assistant.
     *
     * KEY INSIGHT: MODE_NORMAL does NOT reliably activate hardware AEC on most devices.
     * The HAL only enables AEC when MODE_IN_COMMUNICATION is set (same code path as phone calls).
     *
     * Solution (same as WhatsApp/Telegram/Discord speakerphone):
     * 1. MODE_IN_COMMUNICATION → activates HAL AEC pipeline
     * 2. Force speaker routing → audio comes out of speaker (not earpiece)
     *
     * Result: AEC works + speaker output = full-duplex without echo
     */
    fun configureAudioMode() {
        configureAudioMode(isHeadphone = _isHeadphoneMode.value)
    }

    /**
     * Headphone-aware audio mode configuration.
     *
     * - **Speaker mode**: MODE_IN_COMMUNICATION + speaker routing + AEC (standard flow)
     * - **Headphone mode**: MODE_NORMAL, no speaker routing, AEC disabled
     *   (no acoustic echo path with headphones — AEC is unnecessary overhead)
     */
    fun configureAudioMode(isHeadphone: Boolean) {
        _isHeadphoneMode.value = isHeadphone

        if (isHeadphone) {
            // Headphones: MODE_NORMAL is fine, no echo path exists
            audioManager.mode = AudioManager.MODE_NORMAL
            disableAecEffects()
            println("[FullDuplexSession] Headphone mode: MODE_NORMAL (AEC bypassed — no echo path)")
        } else {
            // Speaker: MODE_IN_COMMUNICATION activates HAL AEC
            audioManager.mode = AudioManager.MODE_IN_COMMUNICATION
            enableAecEffects()
            forceSpeakerRouting()
            println("[FullDuplexSession] Speaker mode: MODE_IN_COMMUNICATION (HAL AEC active)")
        }
    }

    /**
     * Disable AEC effect without releasing it (for headphone mode).
     * The effect instance stays alive so it can be re-enabled on unplug.
     */
    fun disableAecEffects() {
        acousticEchoCanceler?.let {
            it.enabled = false
            _aecEnabled.value = false
            println("[FullDuplexSession] AEC disabled (headphone mode)")
        }
    }

    /**
     * Re-enable AEC effect (when switching back to speaker mode).
     */
    fun enableAecEffects() {
        acousticEchoCanceler?.let {
            it.enabled = true
            _aecEnabled.value = true
            println("[FullDuplexSession] AEC re-enabled (speaker mode)")
        }
    }

    /**
     * Force audio output to the built-in speaker while in MODE_IN_COMMUNICATION.
     *
     * API 31+ uses setCommunicationDevice() (modern API).
     * API <31 uses setSpeakerphoneOn() (deprecated but still functional).
     */
    @Suppress("DEPRECATION")
    private fun forceSpeakerRouting() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            // API 31+: Use setCommunicationDevice for explicit speaker routing
            try {
                val speaker = audioManager.availableCommunicationDevices.firstOrNull {
                    it.type == AudioDeviceInfo.TYPE_BUILTIN_SPEAKER
                }
                if (speaker != null) {
                    val success = audioManager.setCommunicationDevice(speaker)
                    println("[FullDuplexSession] Speaker routing (API 31+): setCommunicationDevice=${success}")
                } else {
                    // Fallback: try deprecated method
                    audioManager.isSpeakerphoneOn = true
                    println("[FullDuplexSession] Speaker routing: fallback to setSpeakerphoneOn (no speaker device found)")
                }
            } catch (e: Exception) {
                println("[FullDuplexSession] WARNING: setCommunicationDevice failed, using fallback: ${e.message}")
                audioManager.isSpeakerphoneOn = true
            }
        } else {
            // API <31: setSpeakerphoneOn (deprecated but reliable)
            audioManager.isSpeakerphoneOn = true
            println("[FullDuplexSession] Speaker routing (API <31): setSpeakerphoneOn=true")
        }
    }

    /**
     * Reset audio mode and speaker routing to defaults.
     */
    @Suppress("DEPRECATION")
    fun resetAudioMode() {
        // Reset speaker routing
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.S) {
            try {
                audioManager.clearCommunicationDevice()
            } catch (e: Exception) {
                println("[FullDuplexSession] WARNING: clearCommunicationDevice failed: ${e.message}")
            }
        }
        audioManager.isSpeakerphoneOn = false

        // Reset audio mode
        audioManager.mode = AudioManager.MODE_NORMAL
        println("[FullDuplexSession] Audio mode reset to MODE_NORMAL, speaker routing cleared")
    }

    /**
     * Get diagnostic information about the full-duplex session.
     */
    @Suppress("DEPRECATION")
    fun getDiagnostics(): Map<String, Any> = mapOf(
        "sessionId" to sharedSessionId,
        "isActive" to _isSessionActive.value,
        "isHeadphoneMode" to _isHeadphoneMode.value,
        "aecEnabled" to _aecEnabled.value,
        "aecAvailable" to AcousticEchoCanceler.isAvailable(),
        "nsEnabled" to _nsEnabled.value,
        "nsAvailable" to NoiseSuppressor.isAvailable(),
        "agcEnabled" to _agcEnabled.value,
        "agcAvailable" to AutomaticGainControl.isAvailable(),
        "audioMode" to audioManager.mode,
        "isSpeakerphoneOn" to audioManager.isSpeakerphoneOn,
        "modeInCommunication" to (audioManager.mode == AudioManager.MODE_IN_COMMUNICATION)
    )

    /**
     * Release all resources. Call when the audio session is complete.
     */
    fun release() {
        println("[FullDuplexSession] Releasing full-duplex session (sessionId=$sharedSessionId)")
        releaseEffects()
        sharedSessionId = AudioManager.AUDIO_SESSION_ID_GENERATE
        _isSessionActive.value = false
        resetAudioMode()
    }
}
