package com.lifo.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme - Scala di grigi
val md_theme_light_primary = Color(0xFF424242)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFE0E0E0)
val md_theme_light_onPrimaryContainer = Color(0xFF1A1A1A)
val md_theme_light_secondary = Color(0xFF5A5A5A)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE5E5E5)
val md_theme_light_onSecondaryContainer = Color(0xFF1F1F1F)
val md_theme_light_tertiary = Color(0xFF616161)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFE8E8E8)
val md_theme_light_onTertiaryContainer = Color(0xFF212121)
val md_theme_light_error = Color(0xFF2E2E2E)
val md_theme_light_errorContainer = Color(0xFFEEEEEE)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_onErrorContainer = Color(0xFF0A0A0A)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF1A1A1A)
val md_theme_light_surface = Color(0xFFFAFAFA)
val md_theme_light_onSurface = Color(0xFF1A1A1A)
val md_theme_light_surfaceVariant = Color(0xFFE2E2E2)
val md_theme_light_onSurfaceVariant = Color(0xFF454545)
val md_theme_light_outline = Color(0xFF757575)
val md_theme_light_inverseOnSurface = Color(0xFFF0F0F0)
val md_theme_light_inverseSurface = Color(0xFF303030)
val md_theme_light_inversePrimary = Color(0xFFBDBDBD)
val md_theme_light_shadow = Color(0xFF000000)
val md_theme_light_surfaceTint = Color(0xFF424242)
val md_theme_light_outlineVariant = Color(0xFFC4C4C4)
val md_theme_light_scrim = Color(0xFF000000)

// Surface container colors - Light
val md_theme_light_surfaceContainerLowest = Color(0xFFFFFFFF)
val md_theme_light_surfaceContainerLow = Color(0xFFF5F5F5)
val md_theme_light_surfaceContainer = Color(0xFFEFEFEF)
val md_theme_light_surfaceContainerHigh = Color(0xFFE9E9E9)
val md_theme_light_surfaceContainerHighest = Color(0xFFE3E3E3)

// Dark Theme - Scala di grigi
val md_theme_dark_primary = Color(0xFFBDBDBD)
val md_theme_dark_onPrimary = Color(0xFF262626)
val md_theme_dark_primaryContainer = Color(0xFF3A3A3A)
val md_theme_dark_onPrimaryContainer = Color(0xFFE0E0E0)
val md_theme_dark_secondary = Color(0xFFB8B8B8)
val md_theme_dark_onSecondary = Color(0xFF2A2A2A)
val md_theme_dark_secondaryContainer = Color(0xFF404040)
val md_theme_dark_onSecondaryContainer = Color(0xFFE5E5E5)
val md_theme_dark_tertiary = Color(0xFFC2C2C2)
val md_theme_dark_onTertiary = Color(0xFF2D2D2D)
val md_theme_dark_tertiaryContainer = Color(0xFF424242)
val md_theme_dark_onTertiaryContainer = Color(0xFFE8E8E8)
val md_theme_dark_error = Color(0xFFD4D4D4)
val md_theme_dark_errorContainer = Color(0xFF1A1A1A)
val md_theme_dark_onError = Color(0xFF121212)
val md_theme_dark_onErrorContainer = Color(0xFFEEEEEE)
val md_theme_dark_background = Color(0xFF181818)
val md_theme_dark_onBackground = Color(0xFFE1E1E1)
val md_theme_dark_surface = Color(0xFF171717)
val md_theme_dark_onSurface = Color(0xFFE1E1E1)
val md_theme_dark_surfaceVariant = Color(0xFF282828)
val md_theme_dark_onSurfaceVariant = Color(0xFFC4C4C4)
val md_theme_dark_outline = Color(0xFF8E8E8E)
val md_theme_dark_inverseOnSurface = Color(0xFF2C2C2C)
val md_theme_dark_inverseSurface = Color(0xFFE1E1E1)
val md_theme_dark_inversePrimary = Color(0xFF424242)
val md_theme_dark_shadow = Color(0xFF000000)
val md_theme_dark_surfaceTint = Color(0xFFBDBDBD)
val md_theme_dark_outlineVariant = Color(0xFF454545)
val md_theme_dark_scrim = Color(0xFF000000)

// Surface container colors - Dark
val md_theme_dark_surfaceContainerLowest = Color(0xFF0F0F0F)
val md_theme_dark_surfaceContainerLow = Color(0xFF1A1A1A)
val md_theme_dark_surfaceContainer = Color(0xFF1E1E1E)
val md_theme_dark_surfaceContainerHigh = Color(0xFF252525)
val md_theme_dark_surfaceContainerHighest = Color(0xFF2E2E2E)

// Seed color in scala di grigi
val seed = Color(0xFF7A7A7A)


val NeutralColor = Color(0xFF78909C)
val HappyColor = Color(0xFFFFEE58)
val RomanticColor = Color(0xFFEC407A)
val CalmColor = Color(0xFF42A5F5)
val TenseColor = Color(0xFFFF7043)
val LonelyColor = Color(0xFF8D6E63)
val MysteriousColor = Color(0xFF26A69A)
val AngryColor = Color(0xFFEF5350)
val AwfulColor = Color(0xFF66BB6A)
val SurprisedColor = Color(0xFF29B6F6)
val DepressedColor = Color(0xFFBDBDBD)
val DisappointedColor = Color(0xFFAB47BC)
val ShamefulColor = Color(0xFF7E57C2)
val HumorousColor = Color(0xFFFFCA28)
val SuspiciousColor = Color(0xFFD4E157)
val BoredColor = Color(0xFF26C6DA)
